### ISSUE TITLE
Please provide API to update the animations by time elapsed from animation start

### ISSUE THREAD

**Issue by gizmomogwai** [AlexandrosKap/deetween#1]
First of all, thanks for doing this library ... this got me finally motivated to add some animations to my dlang imageviewer :)

In my usecase it would be simpler to just take the time at the beginning of an animation and feed `Clock.currTime - startOfAnimation` e.g. into a Tween.

an implementation for tween could look like this:
```d
    struct Tween {
    .
    .
    .
    float elapsedTime(float elapsedTime)
    {
        final switch (mode)
        {
        case TweenMode.bomb:
            if (elapsedTime < 0.0f) {
                time = 0.0f;
            } else if (elapsedTime >= duration) {
                time = duration;
            } else {
                time = elapsedTime;
            }
            return now;
        case TweenMode.loop:
        case TweenMode.yoyo:
            assert(0);
        }
    }
    .
    .
    .
```

**Comment by Kapendev** [comment]
So if I understand correctly, you want a way to set the time to something and get the value at that time on the same line?
Like update() but without adding/subtracting from time?

Thanks for trying the library.

**Comment by gizmomogwai** [comment]
Yes ...with update i have to always store update the time of the last call to update, with the additional API I just take the time at start of the animation and subtract the same value from the current time.

Btw. This was for me a just works (tm), well done.

**Comment by Kapendev** [comment]
I implement elapsedTime() for Tween and KeyframeGroup but it is in main for now.
I will make a new version in the next couple of days.

**Comment by gizmomogwai** [comment]
Thanks a lot ... Will update my local git and use it from there ... But not before this evening ;)

**Comment by gizmomogwai** [comment]
Nice .. works for me ...
I like also the implementation .. nice how you dont repeat yourself by reusing `update` in `elapsedTime`. Perhaps it would be more "efficient" to reuse `elapsedTime` in `update` instead (elapsed time just needs to set the time (plus clamping), wheras update always needs todo the `+dt` thing.

**Comment by Kapendev** [comment]
Actually that's not a bad idea. I don't know about performance but it makes more sense I think.

**Comment by gizmomogwai** [comment]
I also do not know about performance (probably not much difference in the end) ... but still :)

**Comment by Kapendev** [comment]
I did some changes and I think that elapsed and update look OK now. Tell me if you see anything strange.

**Comment by gizmomogwai** [comment]
Looks good for me as well ... at least I do not see a difference in my animation :)
you even added some ddocs ;-)

one thing i do in other parts of my program is to use https://dlang.org/library/std/algorithm/comparison/clamp.html ... makes the clamping shorter ... not sure if you want to depend on those parts of std though ... but this is for sure something for another issue :)
